### ISSUE TITLE
Get rid of Redux for Storybook UI

### ISSUE THREAD

**Issue by arunoda** [storybooks/storybook-ui#55]
We use the new react-komposer + mantra directly. This helps people to start hacking Storybook quickly.

### Tasks

* [x] Launch [React Komposer 2](https://github.com/arunoda/react-komposer)
* [x] Launch [Podda](https://github.com/arunoda/podda)
* [x] Use React Komposer 2 
* [ ] Use Podda instead of Redux

**Comment by arunoda** [comment]
Migrating to Podda in not critical at this stage.
So, we can take #58.
